export const CONSTANTS = {
    "NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID":"1epml17e",
    "NEXT_PUBLIC_HIGHLIGHT_OTLP_ENDPOINT":"123",
    "NEXT_PUBLIC_HIGHLIGHT_BACKEND_URL":"123",
    "NEXT_PUBLIC_HIGHLIGHT_SCRIPT_URL":"123",
}