export const TRANSAK_API_KEY_PROD = process.env.TRANSAK_API_KEY_PROD;

const TRANSAK_API_KEY_TEST_LEVII = process.env.TRANSAK_API_KEY_TEST_LEVII;

// const TRANSAK_API_KEY_TEST_PROD_CONNECTED = process.env.TRANSAK_API_KEY_TEST_PROD_CONNECTED

export const TRANSAK_API_KEY_TEST = TRANSAK_API_KEY_TEST_LEVII; // flexibility to replace with TRANSAK_API_KEY_TEST_PROD_CONNECTED

export const MERCURYO_WIDGET_ID_PROD = process.env.MERCURYO_WIDGET_ID_PROD;
export const MERCURYO_SECRET_PROD = process.env.MERCURYO_SECRET_PROD;
export const MERCURYO_WIDGET_ID_TEST = process.env.MERCURYO_WIDGET_ID_TEST;
export const MERCURYO_SECRET_TEST = process.env.MERCURYO_SECRET_TEST;
